### ISSUE TITLE
Disabling Floating Feature

### ISSUE THREAD

**Issue by bahricanyesil** [jakky1/webview_win_floating#1]
Hi, is there a way to disable the floating feature? I want to display it as like an embedded widget with a fixed size in a fixed part of a scrollable screen. Is there a way to do this? If there is, can you provide an example?

**Comment by jakky1** [comment]
The word "floating" doesn't mean it shows on another window.
You can just give it a try, use it as a normal flutter widget. It will work as your wish (embedded).

The word "floating" just hint the developers that all the other flutter widget cannot show on top of the webview.
The webview just like "floating" on all the other flutter widget.

Hmm... maybe the name will make developers misunderstanding... orz

**Comment by bahricanyesil** [comment]
Yes, you got the problem and edited your answer. The problem is just as you mentioned. It can not be put in a scrollable widget. Which package you are indicating?

**Comment by bahricanyesil** [comment]
I moved to the following  package:
[webview_windows](https://pub.dev/packages/webview_windows) 

It doesn't have a problem like this one.

**Comment by jakky1** [comment]
If fps is not a concern (ex. play video, animation), the webview_windows is a better solution indeed :)
If ~200MB dll file added into your app is not a concern, [webview_cef](https://pub.dev/packages/webview_cef) may be the best solution.
