### ISSUE TITLE
windows 7 support

### ISSUE THREAD

**Issue by mohammedX6** [jakky1/webview_win_floating#10]
How to use this on Windows 7 ?

**Comment by jakky1** [comment]
This package use Microsoft WebView2 SDK version 1.0.1418.22
According to [this article](https://blogs.windows.com/msedgedev/2022/12/09/microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1/),
any version below 1.0.1519.0 should support Windows 7 & 8

I have no Windows 7 environment so I cannot debug if this package not working on it...
By the way, Microsoft has already stopped support newer WebView2 on Windows 7 & 8.

**Comment by mohammedX6** [comment]
Thanks for rich replay,
