### ISSUE TITLE
The temporary files are stored next to the .exe file instead of in the directory intended for it

### ISSUE THREAD

**Issue by lukasz-lukasz-lukasz** [jakky1/webview_win_floating#12]
The WebView2 is creating tmp files while running. By default, the files are created next to the .exe file. It can be problematic while installing the app on C: partition in the location where there is no permission to create files next to the .exe file. 

It will be nice to specify some standard directory or allow to specify it at the plugin API level.
While specifying some standard dir(hardcoded), it will be nice to care of situation that the user can have more than a single app using this plugin installed - then these apps can be in a collision if the location of WebView dir is the same - so the path should be rather unique. 

https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32#specifying-a-custom-udf-location
https://github.com/jakky1/webview_win_floating/blob/master/windows/my_webview.cpp#L123

**Comment by jakky1** [comment]
Fixed in 2.2.0

Sample code:
```
String cacheDir = "c:\\test";
var params = WindowsPlatformWebViewControllerCreationParams(
    userDataFolder: cacheDir);
var controller = WebViewController.fromPlatformCreationParams(params);
```
