### ISSUE TITLE
Previous instance not destroyed after hot reload problem?

### ISSUE THREAD

**Issue by 6260coder** [jakky1/webview_win_floating#14]
Hi, when I hot restart (not hot reload) my project, the webpage from the last time persists and stays on top of the new webpage in the webview. Could this be fixed? Is there a workaround? Thank you very much!

**Comment by jakky1** [comment]
You can try to run your code in Android/iOS wtih only `webview_flutter` package (without my `webview_win_floating`), and you will find that this problem also occurs in `webview_flutter` in  Android/iOS.

The webview instance only destroyed when it is [Garbage-Collected](https://dart.googlesource.com/sdk/+/refs/tags/2.15.0-99.0.dev/runtime/docs/gc.md). And garbage-collection only runs when there are large amount of (maybe 10MB / 100MB or others) object (not include C++ object) that not referenced by any Dart-pointer.

An easiest way (but not so good) to force garbage-collection is to run the following code. Please run the following code when you want to dispose that webview.
```
webViewController = null; // your  'WebViewController' instance
List<int>.filled(999999, 0);
```

In normal case, the webview instnace will be 'paused' and 'invisible' when `WebViewWidget` removed from the widget-tree. But it will only be 'destroyed' when garbage-collection occurs and no pointer reference to the 'WebViewController'.

**Comment by 6260coder** [comment]
I tested it on Android. I am not sure if the webview is destroyed after hot restart, but if I load webpage A using WebViewController's loadRequest, change the address to that of webpage B and then hot restart, webpage B would be showing. Whereas with webview_win_floating, after hot restart, the webview would still be showing webpage A, and if I make the webview window larger, I would find webpage B displayed underneath webpage A.

**Comment by jakky1** [comment]
If you can call loadRequest again, it means it is not disposed.

Anyway it shows that even 'webview_flutter' won't disposed in your case.

Regardless of hot relaoding, just talk about normal case,
As what I said, the webview only disposed when dart vm runs garbage collection process, so you must wait until it occurs, or allocate a large memory to force it running.

**Comment by 6260coder** [comment]
Sorry for the late reply but what I desire is that the webpage from before the hot restart won't survive the hot restart and block the view of what's happening in the webview after the hot restart. webview_flutter seems to behave as desired in this regard, but with webview_win_floating the content from before the hot restart would always be shown on top of the current content of the webview.

**Comment by jakky1** [comment]
I'm a little confused...

I try the following code, run  it, 
then click the above "Java" link, and the webpage shows the "Java" content,
then "hot reload" or "Restart",
and the webpage still shows the "Java" content.

Doesn't it match your expectation ?

By the way, your metioned "hot restart" several times. Do you mean "hot reload" or "Restart" ?

```
import 'package:flutter/material.dart';
import 'package:webview_win_floating/webview.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  WindowsWebViewPlatform.registerWith();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WebViewController();

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.setNavigationDelegate(NavigationDelegate(
      onNavigationRequest: (request) => NavigationDecision.navigate,
    ));
    controller.loadRequest(Uri.parse("https://www.w3schools.com/"));
  }

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      home: Scaffold(
        body: WebViewWidget(controller: controller),
      ),
    );
  }
}
```

**Comment by 6260coder** [comment]
Sorry for being late again. I keep forgetting important things. I'm setting an alarm on my phone this time.

The issue I am reporting I think only exists with restarts, not with reloads. If I understand it corretly, my app should lose all its states after a hot restart. Therefore in the scenario you provided, shouldn't one expect the webview to display w3schools' homepage rather than the Java section the user navigated to before the restart? I tested your code on Android going through the steps you mentioned. Picture 1 is what the webview looks like after hot restart.  [Picture 1](https://ibb.co/Gc5TCXJ)
And Picture 2 is what it looks like with webview_win_floating after hot restart. [Picture 2](https://ibb.co/kQvRLYJ)
But as Picture 3 shows, if I enlarge the window, I would find that it is indeed displaying the homepage, but it was hidden underneath the Java section from the last time. [Picture 3](https://ibb.co/jy0jcmf)

**Comment by jakky1** [comment]
I got the point, and I think I fix it.

Please try the new version on github:
```
dependencies:
  webview_win_floating:
    git:
      url: https://github.com/jakky1/webview_win_floating.git
      ref: master
```

**Comment by 6260coder** [comment]
It seems to work as expected now! Amazing! You are a star!
