### ISSUE TITLE
Microsoft Edge can't read and write to its data directory

### ISSUE THREAD

**Issue by duc0103** [jakky1/webview_win_floating#16]
Please help me isuses win10 
![image](https://github.com/jakky1/webview_win_floating/assets/61742824/9c839c06-6d72-49e3-bfa9-022699a0407b)

mycode :

import 'package:flutter/material.dart';
import 'package:webview_win_floating/webview.dart';

void main() {
  WindowsWebViewPlatform.registerWith();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WinWebViewController("C:");

  @override
  void initState() {
    super.initState();
    // controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    /*
    controller.setNavigationDelegate(NavigationDelegate(
      onNavigationRequest: (request) {
        //return NavigationDecision.navigate;
        return NavigationDecision.prevent;
      },
    ));
    */
    controller.loadRequest(Uri.parse("https://www.w3schools.com/"));
  }
  @override
  void dispose() {
    controller.dispose();
    // TODO: implement dispose
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: WinWebViewWidget(controller: controller),
      ),
    );
  }
}

**Comment by jakky1** [comment]
Sorry for late.

Please add `\\` in your path. 
For example:
```
final controller = WinWebViewController("C:\\");
```
