### ISSUE TITLE
get and post issue

### ISSUE THREAD

**Issue by atasismail** [jakky1/webview_win_floating#17]
When entering my website's login section via web browsers, it works fine, but in the webview package, it redirects as a GET request instead of a POST request, so I can't log in using the webview package.

**Comment by atasismail** [comment]
Setting custom headers on POST requests 
Currently, setting custom headers when making a post request with the WebViewController's loadRequest method is not supported on Android. If you require this functionality, a workaround is to make the request manually, and then load the response data using loadHtmlString instead. 


How can I use it?

**Comment by jakky1** [comment]
I found that I couldn't login into https://www.facebook.com/    either,

I fix it, and upload to pub.dev
Please try with the latest version and let me know if it work for you.
```
dependencies:
  webview_win_floating: ^2.2.3
```

**Comment by atasismail** [comment]
Problem solved, thank you very much
