### ISSUE TITLE
Support for latest webview_flutter 4.0.1

### ISSUE THREAD

**Issue by ardivee** [jakky1/webview_win_floating#2]
When trying to add the package with the latest webview_flutter this error shows:

`Because webview_flutter >=4.0.0 depends on webview_flutter_platform_interface ^2.0.0 and every version of webview_win_floating depends on webview_flutter_platform_interface ^1.9.5, webview_flutter >=4.0.0 is incompatible with webview_win_floating.`

**Comment by jakky1** [comment]
I just take a look at the [Migrating from 3.0 to 4.0](https://pub.dev/packages/webview_flutter#migrating-from-30-to-40) in webview_flutter
Hmm... a lot of API changes...

It may take me some time to upgrade to [webview_flutter_platform_interface 2.0.1]
Before I finish it, please... wait... orz

**Comment by jakky1** [comment]
It's all done ... maybe

For the new flutter_webview API, 
in 4.0.1, the WebView seems not destroyed after widget dispose,
but in 3.0.3 the WebView will be destroyed.
I post a new issue to [flutter_webview] [#118539](https://github.com/flutter/flutter/issues/118539)

I will push to pub.dev after I can figure out how to destroy webview in new API 4.0.1
Currently I only push to github.
Currently Windows webview will be dstroyed when WebViewWidget disposed.

Please modify your ``pubspec.yaml`` if you want to upgrade to new API now:
```
dependencies:
  webview_win_floating:
    git:
      url: https://github.com/jakky1/webview_win_floating.git
      ref: master
  webview_flutter: ^4.0.1
```

and the windows webview registration code is changed:
```
WindowsWebViewPlatform.registerWith();
// WebView.platform = WindowsWebViewPlugin(); //old version
```

The README is also updated.

**Comment by ardivee** [comment]
Thank you! Hopefully you'll be able to figure out how to destroy the webview as well.
