### ISSUE TITLE
Youtube embed 

### ISSUE THREAD

**Issue by mohgit97** [jakky1/webview_win_floating#20]
When i tried to embed youtube video i get margin to the right

**Comment by jakky1** [comment]
I run with the following test code, and no problems found.
Please post the screenshot and tell me which part is wrong.

```Dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WebViewController();

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.loadRequest(Uri.parse("https://www.youtube.com/embed/fatb7Clc0MM"));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: WebViewWidget(controller: controller),
      ),
    );
  }
}
```

![image](https://github.com/jakky1/webview_win_floating/assets/13192696/6bfb0b99-214b-400b-aaff-b8228fa350ea)

**Comment by mohgit97** [comment]
the problem was when to re enter to the same screen with the embed video.but the problem solved by dispose any controller in any screen of the app , if you left one controller not disposed you will get the margin bug.

**Comment by jakky1** [comment]
If there is still something wrong,
please post a simple sample code ( < 150 lines) that can duplicate this issue.
I have no idea how to duplicate this issue.

**Comment by mohgit97** [comment]
no the problem was disposing all controllers. thanks for your help
