### ISSUE TITLE
Windows7 uses webview-win-floating, which causes a black screen when Windows lose focus

### ISSUE THREAD

**Issue by doujd** [jakky1/webview_win_floating#23]
Hello, I use webview-win-floating on my Windows7 PC, and when Windows lose focus, or minimize recovery, the window will be black, I hope you can help me look at this problem

**Comment by jakky1** [comment]
I tried it on Windows 11 and it works well.

I have no Windows 7 so I cannot test on it.
This package use Microsoft Webview2, and it doesn't support win7 anymore.
So I won't fix this issue.

https://learn.microsoft.com/zh-tw/microsoft-edge/webview2/
