### ISSUE TITLE
how to set all corners to the webview

### ISSUE THREAD

**Issue by allanGoldZhiKang** [jakky1/webview_win_floating#24]
how to set all corners to the webview

i have used clipBehavior and borderRadius, but it doesn't work

**Comment by jakky1** [comment]
No,
This package doesn't support this.

**Comment by allanGoldZhiKang** [comment]
> No, This package doesn't support this.

Could you explain the principle of how WebView2 on Windows is displayed within Flutter? Thank you.

**Comment by jakky1** [comment]
This package just put a [Microsoft WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2) Win32 control on top of the flutter view, without OpenGL texture involved.
So I called this package a 'floating' webview.

It is drew by itself, so flutter sdk cannot do any post-processing such as clip/setAlpha/scale.
