### ISSUE TITLE
runJavaScript() and loadRequest() doesn't support non-ASCII characters

### ISSUE THREAD

**Issue by jlcool** [jakky1/webview_win_floating#25]
其他没试过，改哪里可以修复呢

**Comment by jakky1** [comment]
Please give me a simple sample code ( < 100 lines ) to reproduce this issue.

I tried with the following code and it works well.
The webview really show google webpage with query "中文" results.
```dart
controller.loadRequest(Uri.parse("https://www.google.com/search?q=中文"));
```

**Comment by jlcool** [comment]
试试runJavaScript(“alert(‘中文’)”)



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jakky1 ***@***.***&gt;
发送时间: 2024年7月29日 18:46
收件人: jakky1/webview_win_floating ***@***.***&gt;
抄送: jlcool ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jakky1/webview_win_floating] runJavaScript、loadRequest_有中文时乱码 (Issue #25)





 
Please give me a simple sample code ( < 100 lines ) to reproduce this issue.
 
I tried with the following code and it works well.
 The webview really show google webpage with query "中文" results.
 controller.loadRequest(Uri.parse("https://www.google.com/search?q=中文"));

**Comment by jakky1** [comment]
Fixed for `runJavaScript()`.

Please try with the new version `2.2.6`

**Comment by jlcool** [comment]
加载本地html时如果路径中有中文也会出问题

**Comment by jakky1** [comment]
The local file path `"c:\中文路徑"` in your code is in wrong format.

Please add `file:///` in the prefix, and use '/' as path separator.
The following code works well:
```dart
controller.loadRequest(Uri.parse("file:///e:/google中文.html"));
```

Here are some wrong path format:
```dart
controller.loadRequest(Uri.parse("file://e:/google中文.html"));   //  only 2 '/' chars after 'file:' 
controller.loadRequest(Uri.parse("e:/google中文.html"));   //  need add 'file:///' as prefix
controller.loadRequest(Uri.parse("e:\\google中文.html"));   //  should use '/' as path separator
```

**Comment by jlcool** [comment]
controller.loadRequest_("c:\中文路径")

> ```dart
> Uri.parse("file://e:/google中文.html")
> ```

我看你controller有个loadRequest_，带下划线方法，是直接加路径就可以了，不需要使用\或者file://，而且有路径中有中文就是会像runJavaScript一样的乱码，windows端调试时看到的。不使用中文路径就没有问题，也证明可能是编码问题

**Comment by jakky1** [comment]
Please ignore the `loadRequest_()` method, it is not public method.

Only report problems if some error occurs with the following code:
```dart
controller.loadRequest(Uri.parse("file:///e:/google中文.html"));
```

**Comment by jlcool** [comment]
非常感谢你的回复，但是loadRequest的问题是一样的，不需要加file://也可以，但是有中文就不行

**Comment by jakky1** [comment]
As I mentioned before,
please add `file:///` at the beginning, this is URI path standard.

**Comment by jakky1** [comment]
As I mentioned before,
please add file:/// at the beginning, this is URI path standard.

Or you can use `Uri.file(...)` instead:
```dart
controller.loadRequest(Uri.file("e:/Google中文.html"));
```

**Comment by jlcool** [comment]
把loadUrl和loadHtmlString中的toWideString替换为utf8ToUtf16后可以了
