### ISSUE TITLE
跨iframe访问时报错Blocked a frame with origin "null" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by jlcool** [jakky1/webview_win_floating#26]
Uncaught DOMException: Failed to set a named property 'ad' on 'Window': Blocked a frame with origin "null" from accessing a cross-origin frame.
要如何开启跨域访问吗？

**Comment by jlcool** [comment]
在my_webview.cpp中的CreateCoreWebView2EnvironmentWithOptions上面添加
``` cpp
wil::com_ptr<ICoreWebView2EnvironmentOptions> options;
options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
options->put_AdditionalBrowserArguments(L"--disable-web-security");
```
修改CreateCoreWebView2EnvironmentWithOptions第三个参数为options.get()

**Comment by jakky1** [comment]
由於這個參數會導致安全性降低
此套件不會支援這個參數
有需要的話請自行 fork 並修改
