### ISSUE TITLE
连续打开三个页面后使用history.back()会有问题

### ISSUE THREAD

**Issue by jlcool** [jakky1/webview_win_floating#28]
连续打开A->B->C后，在C执行back()可以返回B，到B后执行back()会回到C无法到A。
在flutter中使用controller.goBack()可以正确返回
请问怎么回事

**Comment by jakky1** [comment]
I run the following code, and it works well.
Does it work on your PC ?

steps:
```
1. enter 'TV' in search box, press Enter
2. click page [2]
3. click page [3]
4. click [Back] button, and it shows page 2
5. click [Back] button again, and it shows page 1
```

```dart
import 'dart:convert' show utf8;
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_win_floating/webview_win_floating.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WinWebViewController();

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.setBackgroundColor(Colors.cyanAccent);
    controller.loadRequest(Uri.parse("https://www.google.com/"));
  }

  @override
  Widget build(BuildContext context) {
    Widget buttonRow = Row(children: [
      MyCircleButton(icon: Icons.arrow_back, onTap: controller.goBack),
      MyCircleButton(icon: Icons.arrow_forward, onTap: controller.goForward),
      MyCircleButton(icon: Icons.refresh, onTap: controller.reload),
    ]);

    Widget body = Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
      buttonRow,
      Expanded(child: WinWebViewWidget(controller: controller)),
    ]);

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Windows Webview example app'),
        ),
        body: body,
      ),
    );
  }
}

class MyCircleButton extends StatelessWidget {
  final GestureTapCallback? onTap;
  final IconData icon;
  final double size;

  const MyCircleButton(
      {super.key, required this.onTap, required this.icon, this.size = 32});

  @override
  Widget build(BuildContext context) {
    return ClipOval(
      child: Material(
        color: Colors.blue, // Button color
        child: InkWell(
          splashColor: Colors.red, // Splash color
          onTap: onTap,
          child: SizedBox(width: size, height: size, child: Icon(icon)),
        ),
      ),
    );
  }
}

```

**Comment by jlcool** [comment]
是JavaScript的history.back()有问题，controller的go back没有问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jakky1 ***@***.***&gt;
发送时间: 2024年8月6日 18:37
收件人: jakky1/webview_win_floating ***@***.***&gt;
抄送: jlcool ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jakky1/webview_win_floating] 连续打开三个页面后使用history.back()会有问题 (Issue #28)





 
I run the following code, and it works well.
 Does it work on your PC ?
 
steps:
 1. enter 'TV' in search box, press Enter 2. click page [2] 3. click page [3] 4. click [Back] button, and it shows page 2 5. click [Back] button again, and it shows page 1  import 'dart:convert' show utf8; import 'package:flutter/material.dart'; import 'package:webview_flutter/webview_flutter.dart'; import 'package:webview_win_floating/webview_win_floating.dart'; void main() {   runApp(const MyApp()); } class MyApp extends StatefulWidget {   const MyApp({Key? key}) : super(key: key);   @override   State<MyApp&gt; createState() =&gt; _MyAppState(); } class _MyAppState extends State<MyApp&gt; {   final controller = WinWebViewController();   @override   void initState() {     super.initState();     controller.setJavaScriptMode(JavaScriptMode.unrestricted);     controller.setBackgroundColor(Colors.cyanAccent);     controller.loadRequest(Uri.parse("https://www.google.com/"));   }   @override   Widget build(BuildContext context) {     Widget buttonRow = Row(children: [       MyCircleButton(icon: Icons.arrow_back, onTap: controller.goBack),       MyCircleButton(icon: Icons.arrow_forward, onTap: controller.goForward),       MyCircleButton(icon: Icons.refresh, onTap: controller.reload),     ]);     Widget body = Column(       crossAxisAlignment: CrossAxisAlignment.stretch,       children: [       buttonRow,       Expanded(child: WinWebViewWidget(controller: controller)),     ]);     return MaterialApp(       home: Scaffold(         appBar: AppBar(           title: const Text('Windows Webview example app'),         ),         body: body,       ),     );   } } class MyCircleButton extends StatelessWidget {   final GestureTapCallback? onTap;   final IconData icon;   final double size;   const MyCircleButton(       {super.key, required this.onTap, required this.icon, this.size = 32});   @override   Widget build(BuildContext context) {     return ClipOval(       child: Material(         color: Colors.blue, // Button color         child: InkWell(           splashColor: Colors.red, // Splash color           onTap: onTap,           child: SizedBox(width: size, height: size, child: Icon(icon)),         ),       ),     );   } }

**Comment by jakky1** [comment]
Fixed with some limitation.

Please try new version `2.2.7`, and remove ```NavigationDelegate.onNavigationRequest()``` if exists in your code.

**Comment by jlcool** [comment]
可以了，你太厉害了！
