### ISSUE TITLE
currently not support writing child on the web?

### ISSUE THREAD

**Issue by wajipu** [jakky1/webview_win_floating#31]
![image](https://github.com/user-attachments/assets/ba08eba6-5284-4432-804e-c064d01fd3d8)

**Comment by jakky1** [comment]
Yes.
All the flutter widgets cannot shown on top of the webview in this package.

This is a limitation that mentioned in the README.

**Comment by wajipu** [comment]
@jakky1 Is there no other solution? Or is webview just like this?

**Comment by wajipu** [comment]
Or give me some ideas, see if I can improve it

**Comment by jakky1** [comment]
You can try webview_windows package.

**Comment by wajipu** [comment]
Well, that's too bad to scroll through the list

**Comment by jakky1** [comment]
If you are experiencing display performance issues with other packages, that's why I created this package.

However, in order to avoid display performance issues, it is inevitable to cause the limitations mentioned above.

There is currently no way to work around this limitation.
