### ISSUE TITLE
The history navigation methods don't work well

### ISSUE THREAD

**Issue by lukasz-lukasz-lukasz** [jakky1/webview_win_floating#4]
These methods doesn't work well:

- controller.canGoBack()
- controller.goBack()
- controller.goForward()
- controller.canGoForward()

The `canGoBack()` and `canGoForward()` returns wrong values. The `canGoForward()` returns `false` even though we should be able to go forward because we have browsing history.

I have investigated it a bit and the wrong values are returned in the `add_HistoryChanged` callback. It seems the issue is caused by logic that allows us to filter and decide which page should be loaded and which not: `WinNavigationDelegate.onNavigationRequest` implemented mainly in `add_NavigationStarting` handler.

**Comment by jakky1** [comment]
Fixed, and pushed to github.
Please give it a try.

**Comment by lukasz-lukasz-lukasz** [comment]
I tested and it works almost perfectly!

I wonder if we should allow going back to `about:blank` or only to the first loaded page? I think we shouldn't if we want to be consistent with how it works for Mobile platforms. I have checked it on Mobile and we can go back to the first loaded page only. 

It seems that change should fix that `utf16Url.compare(L"about:blank") == 0`:
`  if (m_isNowGoBackForward
         || nowLoadingUrl.compare(url.get()) == 0
         || utf16Url.rfind(L"data:text/html;", 0) == 0
         || utf16Url.compare(L"about:blank") == 0) {`
         
If you agree I can create a PR, or you can just commit it, please. :)

**Comment by jakky1** [comment]
I tried to:

 load("about:blank")
-> load("https://www.google.com") 
-> canGoBack() return true
-> call goBack() will show blank page
-> call goForward() will go to google site

It seems there is no problem ?

```
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:webview_win_floating/webview.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  WindowsWebViewPlatform.registerWith();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = WebViewController();
  final srollController = ScrollController();

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.setBackgroundColor(Colors.cyanAccent);
    controller.setNavigationDelegate(NavigationDelegate(
      onNavigationRequest: (request) {
        log("onNavigationRequest");
        if (true) return NavigationDecision.navigate;
        if (request.url.startsWith("https://www.google.com")) {
          return NavigationDecision.navigate;
        } else {
          log("prevent user navigate out of google website!");
          return NavigationDecision.prevent;
        }
      },
      onPageStarted: (url) => print("onPageStarted: $url"),
      onPageFinished: (url) => print("onPageFinished: $url"),
      onWebResourceError: (error) =>
          print("onWebResourceError: ${error.description}"),
    ));
    controller.loadRequest(Uri.parse("about:blank"));
  }

  @override
  Widget build(BuildContext context) {
    Widget webview = WebViewWidget(controller: controller);
    webview = Column(children: [
      Row(children: [
        ElevatedButton(
            onPressed: () async {
              controller.loadRequest(Uri.parse("https://www.google.com"));
            },
            child: const Text("Google")),
        ElevatedButton(
            onPressed: () async {
              bool b = await controller.canGoBack();
              print("canGoBack: $b");
              controller.goBack();
            },
            child: const Text("Back")),
        ElevatedButton(
            onPressed: () async {
              bool b = await controller.canGoForward();
              print("canGoForward: $b");
              controller.goForward();
            },
            child: const Text("Forward")),
      ]),
      Expanded(child: webview),
    ]);

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Windows Webview example app'),
        ),
        body: webview,
      ),
    );
  }
}
```

**Comment by lukasz-lukasz-lukasz** [comment]
Thank you for the example code.

I think the whole trick is about what page you load as the first page. In your example, both Mobile and Windows work the same, indeed.

But if we consider this change:

```
  @override
  void initState() {
    ....
    controller.loadRequest(Uri.parse("https://www.wikipedia.com")); // don't load the blank page as first page
  }
```

Then we have some discrepancies between Mobile and Windows. 
On Mobile, we can't go to the blank page, but it is possible on Windows.

![19_01_2023_17_55_01 -1674147301](https://user-images.githubusercontent.com/119860089/213511523-1f9569b6-2a37-4be9-a039-f3d883b105a8.gif)


That is actually an interesting case because probably there is no perfect answer to how it should work. 
The code I proposed in the previous comment isn't perfect because it will break your example but will work well for mine.
