### ISSUE TITLE
How the component events the mouse wheel zoom

### ISSUE THREAD

**Issue by 903531306** [jakky1/webview_win_floating#9]
"A webpage has a k-line chart on it, which can support mouse wheel zooming. How is it implemented? Is it a function that comes with Windows webview2 or a function that comes with the" webview_flutter "component? I would like to know about its implementation.". thank you

**Comment by jakky1** [comment]
The mouse wheel event works well on this [W3CSchools test page](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onwheel_addeventlistener).

But please make sure you have already CLICKed on the webview before using mouse wheel event.

Before you click the webview, the focus is owned by flutter, so the webview won't receive any keyboard / mouse events .

**Comment by 903531306** [comment]
I wonder if webview2 for Windows supports zooming

**Comment by jakky1** [comment]
Hmm... webview2 can set zoom factor 
but not support zooming by ctrl+wheel

and because this package is not integrated into flutter view hierarachy,
so you cannot listen key/mouse event in dart (but possible in js code),
so it's not possible to listen wheel event and set zoom factor.

**Comment by 903531306** [comment]
ok Thanks

**Comment by jakky1** [comment]
Sorry, I'm now correcting my anwser:

webview2 support ctrl+wheel to zooming (you should CLICK webview2 first)
and it also support developer to set zoom factor (even though official ``webview_flutter`` package not support this API)

**Comment by 903531306** [comment]
Okay, let me take a look at the official API for webview2. Thank you
